server:
  port: 9032
  max-http-header-size: 100000
spring:
  application:
    name: production
  mysql:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.8:3306/sanlly?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: sanlly
        password: Sanlly@123
        maxActive: 30 #连接池最大使用连接数量
        minIdle: 0 #连接池最小空闲
        initialSize: 0   # 初始化连接大小 
        mapperLocations: classpath*:mapper/*.xml
  servlet:
    multipart:
      maxFileSize: 400MB
      maxRequestSize: 400MB
  mvc:
    date-format: yyyy-MM-dd   #date类型参数按照此格式进行日期格式化 
  pdf:
    location: ./pdf/
  edi:
    template-loader-path: classpath:/edi
    timer: false
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    suffix: .ftl
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    settings:
     default_encoding: UTF-8
     output_encoding: UTF-8
     url_escaping_charset: UTF-8
     tag_syntax: auto_detect
     locale: zh_CN
     datetime_format: yyyy-MM-dd HH:mm:ss
     date_format: yyyy-MM-dd
     time_format: HH:mm:ss
     classic_compatible: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
      service-url:
        defaultZone: http://192.168.0.26:8761/eureka/
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS