server:
    port: 8761
    max-http-header-size: 104857600 #100M
    tomcat:
      max-http-header-size: 104857600 #100M
spring:
    application:
        name: eureka-server
eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
# 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
        eviction-interval-timer-in-ms: 20000
        enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS