server:
  port: 9040
  max-http-header-size: 104857600 #100M
  tomcat:
    max-http-header-size: 104857600 #100M
spring:
  application:
    name: workflow
  mysql:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.8:3306/sanlly?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: sanlly
        password: Sanlly@123
        maxActive: 30 #连接池最大使用连接数量
        minIdle: 0 #连接池最小空闲
        initialSize: 0   # 初始化连接大小 
        mapperLocations: classpath*:mapper/*.xml
  servlet:
    multipart:
      maxFileSize: 400MB
      maxRequestSize: 400MB

#freemarker模板配置
  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    contentType: text/html
    requestContextAttribute: ctx
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1
    activiti:
      check-process-definitions: false
      synch-users: false #程序启动，是否同步一次用户和组数据
      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
      service-url:
        defaultZone: http://192.168.0.26:8761/eureka/
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS