server:
  port: 9099
  max-http-header-size: 104857600 #100M
  tomcat:
    max-http-header-size: 104857600 #100M
spring:
  application:
    name: monitor-server
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>鑫三利监控服务</span>
        title: 鑫三利监控服务
eureka:
    instance:
        hostname: localhost
        leaseRenewalIntervalInSeconds: 10
        health-check-url-path: /actuator/health
        metadata-map:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://192.168.0.26:8761/eureka/
    server:
# 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
        eviction-interval-timer-in-ms: 10000
        enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS